- name: Access GlassFish Web Console for validation
  hosts: all
  vars:
    glassfish_url: http://localhost:4848/common/index.jsf
  
  tasks:  
    - name: Accesing GlassFish Web Console for validation
      win_uri:
        url: "{{ glassfish_url }}"
        method: GET
        validate_certs: no
        return_content: yes
        status_code: 200