- name: Start or Stop a windows service Playbook
  hosts: all
  vars:
    service_name: 'GlassFish4'
    service_state: 'started'
  
  tasks:
    - name: Start or stop a windows service
      win_service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"